"use client";
import { useState, useEffect } from "react";
import NetaWatchClient from "../components/NetaWatchClient";
import { SEED_POLITICIANS } from "../lib/seed";
import { scoreBatch } from "../lib/scoring";

export default function Home() {
  const [politicians, setPoliticians] = useState(() => scoreBatch(SEED_POLITICIANS));
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Try to load full MP dataset from public/politicians.json
    // Generated by: node scripts/fetch-mps.js
    fetch("/politicians.json")
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        if (data && data.length > 0) setPoliticians(scoreBatch(data));
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  return (
    <>
      {loading && (
        <div style={{
          position:"fixed", bottom:16, right:16, zIndex:999,
          background:"#111", color:"#22C55E", fontSize:11,
          padding:"8px 14px", borderRadius:6, fontWeight:700,
          letterSpacing:1, fontFamily:"monospace",
          boxShadow:"0 4px 20px rgba(0,0,0,0.3)",
          animation:"pulse 1s infinite"
        }}>● Loading politicians…</div>
      )}
      <NetaWatchClient initialData={politicians} />
    </>
  );
}
