// lib/seed.js
export const SEED_POLITICIANS = [
  {
    id: "1",
    name: "Narendra Modi",
    party: "BJP",
    state: "Gujarat",
    constituency: "Varanasi",
    role: "Prime Minister of India",
    age: 73,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Narendra_Modi_-_2024_%28cropped%29.jpg/240px-Narendra_Modi_-_2024_%28cropped%29.jpg",
    totalAssets:    { 2009: 0.14, 2014: 1.65, 2019: 2.85, 2024: 3.02 },
    liabilities:    { 2009: 0.0,  2014: 0.0,  2019: 0.0,  2024: 0.0  },
    declaredIncome: { 2019: 0.17, 2020: 0.18, 2021: 0.19, 2022: 0.20, 2023: 0.21 },
    holdings: [
      { sector: "Savings & FD",  value: 1.8,  conflict: false },
      { sector: "Real Estate",   value: 1.1,  conflict: false },
      { sector: "Gold",          value: 0.12, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [],
    partyHistory: [{ party: "BJP", from: 1987, to: 2024 }],
    network: [],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 0, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "Oct 2001", event: "Appointed Chief Minister of Gujarat", type: "appt" },
      { date: "May 2014", event: "Elected Prime Minister of India", type: "appt" },
      { date: "May 2019", event: "Re-elected with 303 seats", type: "appt" },
      { date: "Jun 2024", event: "Third term as Prime Minister", type: "appt" },
    ],
  },
  {
    id: "2",
    name: "Rahul Gandhi",
    party: "INC",
    state: "Kerala",
    constituency: "Wayanad",
    role: "Leader of Opposition",
    age: 53,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Rahul_Gandhi_2024.jpg/240px-Rahul_Gandhi_2024.jpg",
    totalAssets:    { 2009: 4.81, 2014: 9.41, 2019: 15.89, 2024: 20.05 },
    liabilities:    { 2009: 0.0,  2014: 0.0,  2019: 0.0,   2024: 0.0  },
    declaredIncome: { 2019: 0.68, 2020: 0.72, 2021: 0.76, 2022: 0.80, 2023: 0.85 },
    holdings: [
      { sector: "Stocks & MF",  value: 8.2,  conflict: false },
      { sector: "Real Estate",  value: 7.4,  conflict: false },
      { sector: "Savings",      value: 4.45, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [
      { case: "Defamation — Modi surname remarks", status: "ACQUITTED", resolvedYear: 2024, note: "Convicted by Surat court, acquitted by Supreme Court 2024" },
      { case: "National Herald case (ED)",         status: "PENDING",   resolvedYear: null, note: "ED investigation ongoing since 2021" },
    ],
    partyHistory: [{ party: "INC", from: 2004, to: 2024 }],
    network: [],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 0, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "Jan 2004", event: "Elected MP from Amethi", type: "appt" },
      { date: "Dec 2017", event: "Elected INC National President", type: "appt" },
      { date: "Mar 2023", event: "Disqualified from Lok Sabha — defamation conviction", type: "legal", flag: true },
      { date: "Aug 2023", event: "Reinstated as MP by Supreme Court", type: "legal" },
      { date: "Jun 2024", event: "Elected from Wayanad and Rae Bareli", type: "appt" },
    ],
  },
  {
    id: "3",
    name: "Amit Shah",
    party: "BJP",
    state: "Gujarat",
    constituency: "Gandhinagar",
    role: "Minister of Home Affairs",
    age: 59,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Amit_Shah_in_2019.jpg/240px-Amit_Shah_in_2019.jpg",
    totalAssets:    { 2009: 2.93, 2014: 8.55, 2019: 25.57, 2024: 39.21 },
    liabilities:    { 2009: 0.28, 2014: 1.10, 2019: 2.34,  2024: 3.10  },
    declaredIncome: { 2019: 0.51, 2020: 0.54, 2021: 0.57, 2022: 0.60, 2023: 0.64 },
    holdings: [
      { sector: "Real Estate",   value: 22.4, conflict: false },
      { sector: "Stocks & MF",   value: 10.8, conflict: false },
      { sector: "Gold & Silver", value: 6.01, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [
      { case: "Sohrabuddin Sheikh encounter (CBI)", status: "ACQUITTED", resolvedYear: 2019, note: "Acquitted by CBI special court, December 2019" },
    ],
    partyHistory: [{ party: "BJP", from: 1983, to: 2024 }],
    network: [],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 0, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "Jan 2014", event: "Appointed BJP National President", type: "appt" },
      { date: "May 2019", event: "Appointed Union Home Minister", type: "appt" },
      { date: "Dec 2019", event: "Acquitted in Sohrabuddin encounter case", type: "legal" },
      { date: "Jun 2024", event: "Re-appointed Home Minister", type: "appt" },
    ],
  },
  {
    id: "4",
    name: "Arvind Kejriwal",
    party: "AAP",
    state: "Delhi",
    constituency: "New Delhi",
    role: "Former Chief Minister of Delhi",
    age: 55,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Arvind_Kejriwal_-_Caricature_%28cropped%29.jpg/240px-Arvind_Kejriwal_-_Caricature_%28cropped%29.jpg",
    totalAssets:    { 2009: 0.32, 2014: 1.17, 2019: 3.40, 2024: 4.02 },
    liabilities:    { 2009: 0.0,  2014: 0.12, 2019: 0.45, 2024: 0.30 },
    declaredIncome: { 2019: 0.21, 2020: 0.22, 2021: 0.23, 2022: 0.24, 2023: 0.25 },
    holdings: [
      { sector: "Real Estate", value: 2.8,  conflict: false },
      { sector: "Savings",     value: 0.92, conflict: false },
      { sector: "Gold",        value: 0.30, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [
      { case: "Delhi liquor policy scam (ED)", status: "PENDING", resolvedYear: null, note: "Arrested March 2024, bail granted by Supreme Court September 2024" },
      { case: "Defamation — Goa CM remarks",   status: "PENDING", resolvedYear: null, note: "Case ongoing in Goa courts" },
    ],
    partyHistory: [{ party: "AAP", from: 2012, to: 2024 }],
    network: [
      { name: "Manish Sisodia", type: "associate", holdingsInConflictSectors: false, tradeBeforePolicy: false, govtContractWon: false, note: "Deputy CM, also arrested in liquor policy case. Bail granted 2024." },
      { name: "Satyendar Jain", type: "associate", holdingsInConflictSectors: false, tradeBeforePolicy: false, govtContractWon: false, note: "Former Minister, arrested in money laundering case 2022." },
    ],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 0, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "Nov 2012", event: "Founded Aam Aadmi Party", type: "party" },
      { date: "Feb 2015", event: "Won Delhi election — 67 of 70 seats", type: "appt" },
      { date: "Mar 2024", event: "Arrested by ED in liquor policy case", type: "legal", flag: true },
      { date: "Sep 2024", event: "Supreme Court grants bail", type: "legal" },
      { date: "Sep 2024", event: "Resigned as Chief Minister of Delhi", type: "appt" },
    ],
  },
  {
    id: "5",
    name: "Smriti Irani",
    party: "BJP",
    state: "Uttar Pradesh",
    constituency: "Amethi",
    role: "Former Minister of Women & Child Development",
    age: 47,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Smriti_Zubin_Irani.jpg/240px-Smriti_Zubin_Irani.jpg",
    totalAssets:    { 2009: 1.20, 2014: 3.72, 2019: 7.64, 2024: 10.21 },
    liabilities:    { 2009: 0.15, 2014: 0.40, 2019: 1.20, 2024: 0.80  },
    declaredIncome: { 2019: 0.44, 2020: 0.46, 2021: 0.49, 2022: 0.52, 2023: 0.55 },
    holdings: [
      { sector: "Real Estate",  value: 5.4,  conflict: false },
      { sector: "Stocks & MF",  value: 3.1,  conflict: false },
      { sector: "Gold",         value: 1.71, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [
      { case: "Illegal bar — Goa excise case", status: "PENDING", resolvedYear: null, note: "Allegations of bar operating in family member's name, case filed 2023" },
    ],
    partyHistory: [{ party: "BJP", from: 2003, to: 2024 }],
    network: [],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 1, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "May 2014", event: "Appointed HRD Minister", type: "appt" },
      { date: "May 2019", event: "Defeated Rahul Gandhi in Amethi", type: "appt" },
      { date: "Jul 2023", event: "Goa bar excise case filed against family", type: "legal", flag: true },
      { date: "Jun 2024", event: "Lost Amethi seat to Congress", type: "appt" },
    ],
  },
  {
    id: "6",
    name: "Mamata Banerjee",
    party: "TMC",
    state: "West Bengal",
    constituency: "Bhawanipore",
    role: "Chief Minister of West Bengal",
    age: 69,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Mamata_Banerjee_-_Kolkata_2011-02-05_2716.jpg/240px-Mamata_Banerjee_-_Kolkata_2011-02-05_2716.jpg",
    totalAssets:    { 2009: 0.07, 2014: 0.14, 2019: 0.96, 2024: 1.10 },
    liabilities:    { 2009: 0.0,  2014: 0.0,  2019: 0.0,  2024: 0.0  },
    declaredIncome: { 2019: 0.12, 2020: 0.13, 2021: 0.14, 2022: 0.15, 2023: 0.16 },
    holdings: [
      { sector: "Savings & FD", value: 0.72, conflict: false },
      { sector: "Real Estate",  value: 0.28, conflict: false },
      { sector: "Gold",         value: 0.10, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [],
    partyHistory: [
      { party: "INC", from: 1970, to: 1997 },
      { party: "TMC", from: 1998, to: 2024 },
    ],
    network: [],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 0, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "Jan 1998", event: "Founded Trinamool Congress, broke from INC", type: "party" },
      { date: "May 2011", event: "Elected Chief Minister of West Bengal", type: "appt" },
      { date: "May 2021", event: "Third consecutive term — TMC wins 213 seats", type: "appt" },
    ],
  },
  {
    id: "7",
    name: "Nirmala Sitharaman",
    party: "BJP",
    state: "Karnataka",
    constituency: "Rajya Sabha",
    role: "Minister of Finance",
    age: 64,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Nirmala_Sitharaman_in_2019.jpg/240px-Nirmala_Sitharaman_in_2019.jpg",
    totalAssets:    { 2014: 1.04, 2019: 1.78, 2024: 3.58 },
    liabilities:    { 2014: 0.0,  2019: 0.0,  2024: 0.0  },
    declaredIncome: { 2019: 0.22, 2020: 0.23, 2021: 0.24, 2022: 0.25, 2023: 0.27 },
    holdings: [
      { sector: "Savings & FD", value: 2.1,  conflict: false },
      { sector: "Gold",         value: 0.98, conflict: false },
      { sector: "Real Estate",  value: 0.50, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [],
    partyHistory: [{ party: "BJP", from: 2008, to: 2024 }],
    network: [],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 0, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "Sep 2017", event: "Appointed Defence Minister — first full-time woman", type: "appt" },
      { date: "May 2019", event: "Appointed Finance Minister of India", type: "appt" },
      { date: "Feb 2020", event: "Presented longest Budget speech in history (2h 42m)", type: "policy" },
      { date: "Jun 2024", event: "Re-appointed Finance Minister", type: "appt" },
    ],
  },
  {
    id: "8",
    name: "Akhilesh Yadav",
    party: "SP",
    state: "Uttar Pradesh",
    constituency: "Kannauj",
    role: "Leader, Samajwadi Party",
    age: 50,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Akhilesh_Yadav_2012.jpg/240px-Akhilesh_Yadav_2012.jpg",
    totalAssets:    { 2009: 2.84, 2014: 13.01, 2019: 28.47, 2024: 44.17 },
    liabilities:    { 2009: 0.30, 2014: 2.10,  2019: 4.20,  2024: 5.80  },
    declaredIncome: { 2019: 0.60, 2020: 0.63, 2021: 0.66, 2022: 0.70, 2023: 0.74 },
    holdings: [
      { sector: "Real Estate",  value: 28.4, conflict: false },
      { sector: "Stocks & MF",  value: 10.2, conflict: false },
      { sector: "Gold",         value: 5.57, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [
      { case: "Disproportionate assets — CBI probe", status: "PENDING", resolvedYear: null, note: "Inquiry initiated 2023, under review" },
    ],
    partyHistory: [{ party: "SP", from: 2000, to: 2024 }],
    network: [],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 0, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "Mar 2012", event: "Elected Chief Minister of UP — youngest ever at 38", type: "appt" },
      { date: "Jan 2017", event: "Elected SP National President", type: "appt" },
      { date: "Mar 2022", event: "SP loses UP election to BJP", type: "appt" },
      { date: "Jun 2024", event: "Elected MP from Kannauj", type: "appt" },
    ],
  },
];
