// lib/seed.js
export const SEED_POLITICIANS = [
  {
    id: "1",
    name: "Narendra Modi",
    party: "BJP",
    state: "Gujarat",
    constituency: "Varanasi",
    role: "Prime Minister of India",
    age: 73,
    // Wikipedia Commons — free to use
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Narendra_Modi_-_2024_%28cropped%29.jpg/240px-Narendra_Modi_-_2024_%28cropped%29.jpg",
    totalAssets:    { 2009: 0.14, 2014: 1.65, 2019: 2.85, 2024: 3.02 },
    liabilities:    { 2009: 0.0,  2014: 0.0,  2019: 0.0,  2024: 0.0  },
    declaredIncome: { 2019: 0.17, 2020: 0.18, 2021: 0.19, 2022: 0.20, 2023: 0.21 },
    holdings: [
      { sector: "Savings & FD",  value: 1.8,  conflict: false },
      { sector: "Real Estate",   value: 1.1,  conflict: false },
      { sector: "Gold",          value: 0.12, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [],
    partyHistory: [
      { party: "BJP", from: 1987, to: 2024 },
    ],
    network: [],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 0, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "Oct 2001", event: "Appointed Chief Minister of Gujarat", type: "appt" },
      { date: "May 2014", event: "Elected Prime Minister", type: "appt" },
      { date: "May 2019", event: "Re-elected with 303 seats", type: "appt" },
      { date: "Jun 2024", event: "Third term as Prime Minister", type: "appt" },
    ],
  },
  {
    id: "2",
    name: "Rahul Gandhi",
    party: "INC",
    state: "Kerala",
    constituency: "Wayanad",
    role: "Leader of Opposition",
    age: 53,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Rahul_Gandhi_2024_%28cropped%29.jpg/240px-Rahul_Gandhi_2024_%28cropped%29.jpg",
    totalAssets:    { 2009: 4.81, 2014: 9.41, 2019: 15.89, 2024: 20.05 },
    liabilities:    { 2009: 0.0,  2014: 0.0,  2019: 0.0,   2024: 0.0  },
    declaredIncome: { 2019: 0.68, 2020: 0.72, 2021: 0.76, 2022: 0.80, 2023: 0.85 },
    holdings: [
      { sector: "Stocks & MF",  value: 8.2,  conflict: false },
      { sector: "Real Estate",  value: 7.4,  conflict: false },
      { sector: "Savings",      value: 4.45, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [
      { case: "Defamation (Modi surname remarks)", status: "ACQUITTED", resolvedYear: 2024, note: "Convicted by Surat court, acquitted by Supreme Court" },
      { case: "National Herald case (ED)",         status: "PENDING",   resolvedYear: null, note: "Investigation ongoing since 2021" },
    ],
    partyHistory: [
      { party: "INC", from: 2004, to: 2024 },
    ],
    network: [],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 0, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "Jan 2004", event: "Joined active politics", type: "party" },
      { date: "Dec 2017", event: "Elected INC President", type: "appt" },
      { date: "Mar 2023", event: "Disqualified from Lok Sabha (defamation)", type: "legal", flag: true },
      { date: "Aug 2023", event: "Reinstated as MP by Supreme Court", type: "legal" },
      { date: "Jun 2024", event: "Elected from Wayanad & Rae Bareli", type: "appt" },
    ],
  },
  {
    id: "3",
    name: "Amit Shah",
    party: "BJP",
    state: "Gujarat",
    constituency: "Gandhinagar",
    role: "Minister of Home Affairs",
    age: 59,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Amit_Shah_2024_%28cropped%29.jpg/240px-Amit_Shah_2024_%28cropped%29.jpg",
    totalAssets:    { 2009: 2.93, 2014: 8.55, 2019: 25.57, 2024: 39.21 },
    liabilities:    { 2009: 0.28, 2014: 1.10, 2019: 2.34,  2024: 3.10  },
    declaredIncome: { 2019: 0.51, 2020: 0.54, 2021: 0.57, 2022: 0.60, 2023: 0.64 },
    holdings: [
      { sector: "Real Estate",   value: 22.4, conflict: false },
      { sector: "Stocks & MF",   value: 10.8, conflict: false },
      { sector: "Gold & Silver", value: 6.01, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [
      { case: "Sohrabuddin Sheikh fake encounter (CBI)", status: "ACQUITTED", resolvedYear: 2019, note: "Acquitted by CBI court" },
    ],
    partyHistory: [
      { party: "BJP", from: 1983, to: 2024 },
    ],
    network: [],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 0, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "Jan 2014", event: "Appointed BJP National President", type: "appt" },
      { date: "Nov 2014", event: "Elected to Rajya Sabha from Gujarat", type: "appt" },
      { date: "May 2019", event: "Appointed Home Minister of India", type: "appt" },
      { date: "Apr 2019", event: "CBI court acquittal in Sohrabuddin case", type: "legal" },
      { date: "Jun 2024", event: "Re-appointed Home Minister", type: "appt" },
    ],
  },
  {
    id: "4",
    name: "Arvind Kejriwal",
    party: "AAP",
    state: "Delhi",
    constituency: "New Delhi",
    role: "Former Chief Minister of Delhi",
    age: 55,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/forty/Arvind_Kejriwal_2023_%28cropped%29.jpg/240px-Arvind_Kejriwal_2023_%28cropped%29.jpg",
    totalAssets:    { 2009: 0.32, 2014: 1.17, 2019: 3.40, 2024: 4.02 },
    liabilities:    { 2009: 0.0,  2014: 0.12, 2019: 0.45, 2024: 0.30 },
    declaredIncome: { 2019: 0.21, 2020: 0.22, 2021: 0.23, 2022: 0.24, 2023: 0.25 },
    holdings: [
      { sector: "Real Estate", value: 2.8,  conflict: false },
      { sector: "Savings",     value: 0.92, conflict: false },
      { sector: "Gold",        value: 0.30, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [
      { case: "Delhi liquor policy scam (ED/CBI)", status: "PENDING", resolvedYear: null, note: "Arrested March 2024, granted bail by Supreme Court Sept 2024" },
      { case: "Defamation (Goa CM remarks)",       status: "PENDING", resolvedYear: null, note: "Case ongoing" },
    ],
    partyHistory: [
      { party: "AAP", from: 2012, to: 2024 },
    ],
    network: [
      { name: "Manish Sisodia",  type: "associate", holdingsInConflictSectors: false, tradeBeforePolicy: false, govtContractWon: false, note: "Also arrested in liquor policy case" },
      { name: "Satyendar Jain", type: "associate", holdingsInConflictSectors: false, tradeBeforePolicy: false, govtContractWon: false, note: "Arrested in money laundering case" },
    ],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 0, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "Nov 2012", event: "Founded Aam Aadmi Party", type: "party" },
      { date: "Feb 2015", event: "Elected CM Delhi with 67/70 seats", type: "appt" },
      { date: "Mar 2024", event: "Arrested by ED in liquor policy case", type: "legal", flag: true },
      { date: "Sep 2024", event: "Bail granted by Supreme Court", type: "legal" },
      { date: "Sep 2024", event: "Resigned as Chief Minister", type: "appt" },
    ],
  },
  {
    id: "5",
    name: "Smriti Irani",
    party: "BJP",
    state: "Uttar Pradesh",
    constituency: "Amethi",
    role: "Former Minister of Women & Child Development",
    age: 47,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Smriti_Irani_2023_%28cropped%29.jpg/240px-Smriti_Irani_2023_%28cropped%29.jpg",
    totalAssets:    { 2009: 1.20, 2014: 3.72, 2019: 7.64, 2024: 10.21 },
    liabilities:    { 2009: 0.15, 2014: 0.40, 2019: 1.20, 2024: 0.80  },
    declaredIncome: { 2019: 0.44, 2020: 0.46, 2021: 0.49, 2022: 0.52, 2023: 0.55 },
    holdings: [
      { sector: "Real Estate",  value: 5.4,  conflict: false },
      { sector: "Stocks & MF",  value: 3.1,  conflict: false },
      { sector: "Gold",         value: 1.71, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [
      { case: "Illegal bar/restaurant (Goa)", status: "PENDING", resolvedYear: null, note: "Excise case filed 2023, allegations of underage bartending" },
    ],
    partyHistory: [
      { party: "BJP", from: 2003, to: 2024 },
    ],
    network: [],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 1, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "May 2014", event: "Appointed HRD Minister", type: "appt" },
      { date: "May 2019", event: "Defeated Rahul Gandhi in Amethi", type: "appt" },
      { date: "Jul 2023", event: "Goa bar case filed against family", type: "legal", flag: true },
      { date: "Jun 2024", event: "Lost Amethi seat to Congress", type: "appt" },
    ],
  },
  {
    id: "6",
    name: "Mamata Banerjee",
    party: "TMC",
    state: "West Bengal",
    constituency: "Bhawanipore",
    role: "Chief Minister of West Bengal",
    age: 69,
    photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Mamata_Banerjee_2023_%28cropped%29.jpg/240px-Mamata_Banerjee_2023_%28cropped%29.jpg",
    totalAssets:    { 2009: 0.07, 2014: 0.14, 2019: 0.96, 2024: 1.10 },
    liabilities:    { 2009: 0.0,  2014: 0.0,  2019: 0.0,  2024: 0.0  },
    declaredIncome: { 2019: 0.12, 2020: 0.13, 2021: 0.14, 2022: 0.15, 2023: 0.16 },
    holdings: [
      { sector: "Savings & FD", value: 0.72, conflict: false },
      { sector: "Real Estate",  value: 0.28, conflict: false },
      { sector: "Gold",         value: 0.10, conflict: false },
    ],
    tradeEvents: [],
    criminalCases: [],
    partyHistory: [
      { party: "INC", from: 1970, to: 1997 },
      { party: "TMC", from: 1998, to: 2024 },
    ],
    network: [],
    disclosure: { lateFilings: 0, amendmentsAfterMedia: 0, assetsFoundInAudit: 0, missingYears: 0 },
    timeline: [
      { date: "Jan 1998", event: "Founded Trinamool Congress", type: "party" },
      { date: "May 2011", event: "Elected Chief Minister of West Bengal", type: "appt" },
      { date: "May 2021", event: "Third consecutive term as CM", type: "appt" },
    ],
  },
];
